"""v5.8

Revision ID: 04610073fd1c
Revises: 7627ef0136be
Create Date: 2026-08-11 13:40:54.478399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04610073fd1c"
down_revision: Union[str, Sequence[str], None] = "7627ef0136be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "courier_profile", "is_ready", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column("user", "bio", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "user", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("user", "bio", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "courier_profile", "is_ready", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###
