"""v4.8 one image

Revision ID: 05a08afa0fbd
Revises: 00cadc7d83c4
Create Date: 2026-08-11 10:28:28.872894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a08afa0fbd'
down_revision: Union[str, Sequence[str], None] = '00cadc7d83c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shop_banner_id_fkey'), 'shop', type_='foreignkey')
    op.drop_column('shop', 'banner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('banner_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('shop_banner_id_fkey'), 'shop', 'media', ['banner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
