"""fix nullable#2

Revision ID: 1a62f4009547
Revises: 709a24d9be43
Create Date: 2026-10-04 07:11:12.346454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a62f4009547'
down_revision: Union[str, Sequence[str], None] = '709a24d9be43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shop_rating_user_id_key'), 'shop_rating', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('shop_rating_user_id_key'), 'shop_rating', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
