"""v4.2

Revision ID: 25e7ae91fda3
Revises: 41bc9049fed5
Create Date: 2026-08-10 12:43:41.160848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25e7ae91fda3"
down_revision: Union[str, Sequence[str], None] = "41bc9049fed5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("age", sa.SmallInteger(), nullable=False))
    op.add_column("user", sa.Column("bio", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "bio")
    op.drop_column("user", "age")
    # ### end Alembic commands ###
