"""v6.8 add: audit_log table

Revision ID: 41282b6cec2f
Revises: adfd6e42738a
Create Date: 2026-09-20 18:53:35.412377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41282b6cec2f'
down_revision: Union[str, Sequence[str], None] = 'adfd6e42738a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('user_id', sa.SmallInteger(), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=True),
    sa.Column('target_table', sa.String(length=50), nullable=True),
    sa.Column('target_table_id', sa.SmallInteger(), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_bucket_id'), 'bucket', ['id'], unique=False)
    op.create_index(op.f('ix_bucket_product_id'), 'bucket_product', ['id'], unique=False)
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=False)
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.create_index(op.f('ix_courier_profile_id'), 'courier_profile', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_process_id'), 'delivery_process', ['id'], unique=False)
    op.create_index(op.f('ix_discount_id'), 'discount', ['id'], unique=False)
    op.create_index(op.f('ix_like_id'), 'like', ['id'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_item_id'), 'order_item', ['id'], unique=False)
    op.create_index(op.f('ix_payment_process_id'), 'payment_process', ['id'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_media_id'), 'product_media', ['id'], unique=False)
    op.create_index(op.f('ix_promo_code_id'), 'promo_code', ['id'], unique=False)
    op.create_index(op.f('ix_promo_code_report_id'), 'promo_code_report', ['id'], unique=False)
    op.create_index(op.f('ix_region_id'), 'region', ['id'], unique=False)
    op.create_index(op.f('ix_shop_id'), 'shop', ['id'], unique=False)
    op.create_index(op.f('ix_shop_product_id'), 'shop_product', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_log_id'), 'transaction_log', ['id'], unique=False)
    op.alter_column('user', 'is_merchant',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_manager',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_address_id'), 'user_address', ['id'], unique=False)
    op.create_index(op.f('ix_user_notification_id'), 'user_notification', ['id'], unique=False)
    op.alter_column('user_rating', 'user_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('user_rating', 'product_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.create_index(op.f('ix_user_rating_id'), 'user_rating', ['id'], unique=False)
    op.alter_column('user_search', 'user_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.create_index(op.f('ix_user_search_id'), 'user_search', ['id'], unique=False)
    op.alter_column('user_session_token', 'user_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.create_index(op.f('ix_user_session_token_id'), 'user_session_token', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_id'), 'wallet', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_id'), table_name='wallet')
    op.drop_index(op.f('ix_user_session_token_id'), table_name='user_session_token')
    op.alter_column('user_session_token', 'user_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_index(op.f('ix_user_search_id'), table_name='user_search')
    op.alter_column('user_search', 'user_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_index(op.f('ix_user_rating_id'), table_name='user_rating')
    op.alter_column('user_rating', 'product_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('user_rating', 'user_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_index(op.f('ix_user_notification_id'), table_name='user_notification')
    op.drop_index(op.f('ix_user_address_id'), table_name='user_address')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('user', 'is_manager',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_merchant',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_transaction_log_id'), table_name='transaction_log')
    op.drop_index(op.f('ix_shop_product_id'), table_name='shop_product')
    op.drop_index(op.f('ix_shop_id'), table_name='shop')
    op.drop_index(op.f('ix_region_id'), table_name='region')
    op.drop_index(op.f('ix_promo_code_report_id'), table_name='promo_code_report')
    op.drop_index(op.f('ix_promo_code_id'), table_name='promo_code')
    op.drop_index(op.f('ix_product_media_id'), table_name='product_media')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_payment_process_id'), table_name='payment_process')
    op.drop_index(op.f('ix_order_item_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_like_id'), table_name='like')
    op.drop_index(op.f('ix_discount_id'), table_name='discount')
    op.drop_index(op.f('ix_delivery_process_id'), table_name='delivery_process')
    op.drop_index(op.f('ix_courier_profile_id'), table_name='courier_profile')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_index(op.f('ix_bucket_product_id'), table_name='bucket_product')
    op.drop_index(op.f('ix_bucket_id'), table_name='bucket')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
