"""v4_migrate

Revision ID: 41bc9049fed5
Revises: d75bf644cb0c
Create Date: 2026-08-10 12:07:38.246138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41bc9049fed5'
down_revision: Union[str, Sequence[str], None] = 'd75bf644cb0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Avval order jadvalidan status_id Foreign Key va ustunni o'chiramiz
    op.drop_constraint(op.f('order_status_id_fkey'), 'order', type_='foreignkey')
    op.drop_column('order', 'status_id')
    
    # 2. Yangi status ustunini qo'shamiz
    op.add_column('order', sa.Column('status', sa.String(length=100), nullable=False))
    
    # 3. Endi status jadvalini bemalol o'chirsak bo'ladi (chunki bog'liqlik qolmaydi)
    op.drop_table('status')
    
    # 4. Qolgan o'zgarishlar (o'z o'rnida qoladi)
    op.add_column('product', sa.Column('rating', sa.SmallInteger(), nullable=False))
    op.add_column('product', sa.Column('liked_count', sa.BigInteger(), nullable=False))
    op.add_column('user', sa.Column('tell_number', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))  # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'tell_number')
    op.drop_column('product', 'liked_count')
    op.drop_column('product', 'rating')
    op.add_column('order', sa.Column('status_id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('order_status_id_fkey'), 'order', 'status', ['status_id'], ['id'], ondelete='SET NULL')
    op.drop_column('order', 'status')
    op.create_table('status',
    sa.Column('status_method', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('status_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('status_pkey'))
    )
    # ### end Alembic commands ###
