"""v6_8 add: is_checked, category for discount

Revision ID: 44ff4f1dcf54
Revises: 41282b6cec2f
Create Date: 2026-09-22 12:16:07.069799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ff4f1dcf54'
down_revision: Union[str, Sequence[str], None] = '41282b6cec2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket_product', sa.Column('is_checked', sa.Boolean(), nullable=False))
    op.add_column('discount', sa.Column('category', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discount', 'category')
    op.drop_column('bucket_product', 'is_checked')
    # ### end Alembic commands ###
