"""v6.3 delete password.2

Revision ID: 55973b59c834
Revises: 8ef6ba33db28
Create Date: 2026-09-03 15:22:57.520096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55973b59c834"
down_revision: Union[str, Sequence[str], None] = "8ef6ba33db28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password_hash",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=250),
        nullable=False,
    )
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "password", sa.VARCHAR(length=250), autoincrement=False, nullable=False
        ),
    )
    op.alter_column(
        "user",
        "password_hash",
        existing_type=sa.String(length=250),
        type_=sa.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###
