"""v7.1 fix enums

Revision ID: 576f7551e55a
Revises: 98020c33a177
Create Date: 2026-09-23 13:32:11.409059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576f7551e55a'
down_revision: Union[str, Sequence[str], None] = '98020c33a177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_request', 'request_role',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('MERCHANT', 'COURIER', 'MANAGER', 'ADMIN', name='chooserolerequest', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_request', 'request_role',
               existing_type=sa.Enum('MERCHANT', 'COURIER', 'MANAGER', 'ADMIN', name='chooserolerequest', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
