"""fix nullable

Revision ID: 709a24d9be43
Revises: 889a9b77669f
Create Date: 2026-10-02 14:25:23.174226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709a24d9be43'
down_revision: Union[str, Sequence[str], None] = '889a9b77669f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('order', 'address_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('payment_process', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('payment_process', 'order_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('payment_process', 'wallet_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('product_media', 'product_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('product_media', 'media_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('region', 'country_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('role_request', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('shop_rating', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('shop_rating_shop_id_key'), 'shop_rating', type_='unique')
    op.create_unique_constraint('uniq_user_shop_rating', 'shop_rating', ['user_id', 'shop_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_user_shop_rating', 'shop_rating', type_='unique')
    op.create_unique_constraint(op.f('shop_rating_shop_id_key'), 'shop_rating', ['shop_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('shop_rating', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('role_request', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('region', 'country_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('product_media', 'media_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('product_media', 'product_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('payment_process', 'wallet_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('payment_process', 'order_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('payment_process', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('order', 'address_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('order', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
