"""v6.6 fix is_active

Revision ID: 7743a4bae831
Revises: 18fbe1beecfd
Create Date: 2026-09-17 13:15:03.277091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7743a4bae831'
down_revision: Union[str, Sequence[str], None] = '18fbe1beecfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'image_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('user', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('shop', 'image_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
