"""v6.2 delete product_category

Revision ID: 8ef6ba33db28
Revises: d27fbc0c1b81
Create Date: 2026-08-29 00:55:26.711772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ef6ba33db28"
down_revision: Union[str, Sequence[str], None] = "d27fbc0c1b81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("category_id", sa.SmallInteger(), nullable=True))
    op.create_foreign_key(
        None, "product", "category", ["category_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product", type_="foreignkey")
    op.drop_column("product", "category_id")
    # ### end Alembic commands ###
