"""v7.0 change role_request enums

Revision ID: 98020c33a177
Revises: eea33b2d9fee
Create Date: 2026-09-23 13:18:19.572925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98020c33a177'
down_revision: Union[str, Sequence[str], None] = 'eea33b2d9fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_request', 'request_role',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('SINGLE', 'ALL', 'ACTIVE_USER', 'MERCHANTS', 'COURIERS', 'MANAGERS', name='managenotificationcreate', native_enum=False),
               existing_nullable=False)
    op.alter_column('role_request', 'resume_url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('role_request', 'checking_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='rolerequeststatus', native_enum=False),
               nullable=False)
    op.alter_column('role_request', 'reviewed_by',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_request', 'reviewed_by',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('role_request', 'checking_status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='rolerequeststatus', native_enum=False),
               type_=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('role_request', 'resume_url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('role_request', 'request_role',
               existing_type=sa.Enum('SINGLE', 'ALL', 'ACTIVE_USER', 'MERCHANTS', 'COURIERS', 'MANAGERS', name='managenotificationcreate', native_enum=False),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
