"""v5.6

Revision ID: 9cfbc3061f92
Revises: 4a733ff0c4da
Create Date: 2026-08-11 13:27:22.744414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9cfbc3061f92"
down_revision: Union[str, Sequence[str], None] = "4a733ff0c4da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "image_id", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "image_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
