"""v7.2 add:shop_rating table

Revision ID: a56fa3c1a358
Revises: 576f7551e55a
Create Date: 2026-09-25 13:21:53.450369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56fa3c1a358'
down_revision: Union[str, Sequence[str], None] = '576f7551e55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_rating',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('rating_ball', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_shop_rating_id'), 'shop_rating', ['id'], unique=False)
    op.alter_column('audit_log', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('audit_log', 'target_table_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('bucket', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('bucket_product', 'bucket_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('bucket_product', 'product_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('comment', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('comment', 'product_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('courier_profile', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('delivery_process', 'courier_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('delivery_process', 'order_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('delivery_process', 'address_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('like', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('like', 'product_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('order', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('order', 'address_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('order_item', 'order_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('order_item', 'product_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payment_process', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payment_process', 'order_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payment_process', 'wallet_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('product', 'discount_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('product', 'category_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('product_media', 'product_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('product_media', 'media_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('promo_code_report', 'promo_code_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('promo_code_report', 'order_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('promo_code_report', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('region', 'country_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('role_request', 'reviewed_by',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('role_request', 'attempt_count',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_column('shop', 'rating')
    op.alter_column('shop_product', 'shop_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('shop_product', 'product_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('transaction_log', 'payment_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('transaction_log', 'wallet_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user', 'age',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('user_address', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_address', 'region_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_notification', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_notification', 'notification_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_rating', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_rating', 'product_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_rating', 'ball',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('user_search', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_search', 'product_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('user_session_token', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('wallet', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('user_session_token', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('user_search', 'product_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('user_search', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('user_rating', 'ball',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('user_rating', 'product_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('user_rating', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('user_notification', 'notification_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('user_notification', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('user_address', 'region_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('user_address', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('user', 'age',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('transaction_log', 'wallet_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('transaction_log', 'payment_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('shop_product', 'product_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('shop_product', 'shop_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.add_column('shop', sa.Column('rating', sa.BIGINT(), autoincrement=False, nullable=False))
    op.alter_column('role_request', 'attempt_count',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('role_request', 'reviewed_by',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('region', 'country_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('promo_code_report', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('promo_code_report', 'order_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('promo_code_report', 'promo_code_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('product_media', 'media_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('product_media', 'product_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('product', 'category_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('product', 'discount_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('payment_process', 'wallet_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('payment_process', 'order_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('payment_process', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('order_item', 'product_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('order_item', 'order_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('order', 'address_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('order', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('like', 'product_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('like', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('delivery_process', 'address_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('delivery_process', 'order_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('delivery_process', 'courier_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('courier_profile', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('comment', 'product_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('comment', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('bucket_product', 'product_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('bucket_product', 'bucket_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('bucket', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('audit_log', 'target_table_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('audit_log', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_shop_rating_id'), table_name='shop_rating')
    op.drop_table('shop_rating')
    # ### end Alembic commands ###
