"""add: manager, staff=>merchant

Revision ID: adfd6e42738a
Revises: 7743a4bae831
Create Date: 2026-09-20 15:24:33.130846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfd6e42738a'
down_revision: Union[str, Sequence[str], None] = '7743a4bae831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_merchant', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_manager', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_manager')
    op.drop_column('user', 'is_merchant')
    # ### end Alembic commands ###
