"""v6.4 sth add

Revision ID: bb925a98f2e2
Revises: 6a45f74d1b58
Create Date: 2026-09-03 17:31:38.285234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb925a98f2e2"
down_revision: Union[str, Sequence[str], None] = "6a45f74d1b58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "first_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column("user", "age", existing_type=sa.SMALLINT(), nullable=True)
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column("user", "age", existing_type=sa.SMALLINT(), nullable=False)
    op.alter_column(
        "user", "first_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
