"""v6.2 add user search

Revision ID: d27fbc0c1b81
Revises: fdbf07b12c8e
Create Date: 2026-08-20 15:00:47.191277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d27fbc0c1b81"
down_revision: Union[str, Sequence[str], None] = "fdbf07b12c8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_search",
        sa.Column("user_id", sa.SmallInteger(), nullable=True),
        sa.Column("product_id", sa.SmallInteger(), nullable=True),
        sa.Column("query_text", sa.String(length=255), nullable=False),
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_search")
    # ### end Alembic commands ###
