"""v6_9 add: role_request table

Revision ID: eea33b2d9fee
Revises: 44ff4f1dcf54
Create Date: 2026-09-23 05:24:00.556172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea33b2d9fee'
down_revision: Union[str, Sequence[str], None] = '44ff4f1dcf54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_request',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('request_role', sa.Boolean(), nullable=False),
    sa.Column('application', sa.Text(), nullable=True),
    sa.Column('resume_url', sa.String(length=250), nullable=False),
    sa.Column('checking_status', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.SmallInteger(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_code', sa.String(length=255), nullable=True),
    sa.Column('attempt_count', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_request_id'), 'role_request', ['id'], unique=False)
    op.alter_column('audit_log', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('audit_log_id_seq'::regclass)"))
    op.alter_column('bucket', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('bucket_id_seq'::regclass)"))
    op.alter_column('bucket_product', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('bucket_product_id_seq'::regclass)"))
    op.alter_column('category', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('category_id_seq'::regclass)"))
    op.alter_column('comment', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('comment_id_seq'::regclass)"))
    op.alter_column('country', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('country_id_seq'::regclass)"))
    op.alter_column('courier_profile', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('courier_profile_id_seq'::regclass)"))
    op.alter_column('delivery_process', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('delivery_process_id_seq'::regclass)"))
    op.alter_column('discount', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('discount_id_seq'::regclass)"))
    op.alter_column('like', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('like_id_seq'::regclass)"))
    op.alter_column('media', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('media_id_seq'::regclass)"))
    op.add_column('notification', sa.Column('target_role', sa.Enum('SINGLE', 'ALL', 'ACTIVE_USER', 'MERCHANTS', 'COURIERS', 'MANAGERS', name='managenotificationcreate', native_enum=False), nullable=False))
    op.alter_column('notification', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('notification_id_seq'::regclass)"))
    op.alter_column('order', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('order_id_seq'::regclass)"))
    op.alter_column('order_item', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('order_item_id_seq'::regclass)"))
    op.alter_column('payment_process', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('payment_process_id_seq'::regclass)"))
    op.alter_column('product', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('product_id_seq'::regclass)"))
    op.alter_column('product_media', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('product_media_id_seq'::regclass)"))
    op.alter_column('promo_code', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('promo_code_id_seq'::regclass)"))
    op.alter_column('promo_code_report', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('promo_code_report_id_seq'::regclass)"))
    op.alter_column('region', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('region_id_seq'::regclass)"))
    op.alter_column('shop', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('shop_id_seq'::regclass)"))
    op.alter_column('shop_product', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('shop_product_id_seq'::regclass)"))
    op.alter_column('transaction_log', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('transaction_log_id_seq'::regclass)"))
    op.alter_column('user', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))
    op.alter_column('user_address', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_address_id_seq'::regclass)"))
    op.alter_column('user_notification', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_notification_id_seq'::regclass)"))
    op.alter_column('user_rating', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_rating_id_seq'::regclass)"))
    op.alter_column('user_search', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_search_id_seq'::regclass)"))
    op.alter_column('user_session_token', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_session_token_id_seq'::regclass)"))
    op.alter_column('wallet', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('wallet_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('wallet_id_seq'::regclass)"))
    op.alter_column('user_session_token', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_session_token_id_seq'::regclass)"))
    op.alter_column('user_search', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_search_id_seq'::regclass)"))
    op.alter_column('user_rating', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_rating_id_seq'::regclass)"))
    op.alter_column('user_notification', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_notification_id_seq'::regclass)"))
    op.alter_column('user_address', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_address_id_seq'::regclass)"))
    op.alter_column('user', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))
    op.alter_column('transaction_log', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('transaction_log_id_seq'::regclass)"))
    op.alter_column('shop_product', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('shop_product_id_seq'::regclass)"))
    op.alter_column('shop', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('shop_id_seq'::regclass)"))
    op.alter_column('region', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('region_id_seq'::regclass)"))
    op.alter_column('promo_code_report', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('promo_code_report_id_seq'::regclass)"))
    op.alter_column('promo_code', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('promo_code_id_seq'::regclass)"))
    op.alter_column('product_media', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('product_media_id_seq'::regclass)"))
    op.alter_column('product', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('product_id_seq'::regclass)"))
    op.alter_column('payment_process', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('payment_process_id_seq'::regclass)"))
    op.alter_column('order_item', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('order_item_id_seq'::regclass)"))
    op.alter_column('order', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('order_id_seq'::regclass)"))
    op.alter_column('notification', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('notification_id_seq'::regclass)"))
    op.drop_column('notification', 'target_role')
    op.alter_column('media', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('media_id_seq'::regclass)"))
    op.alter_column('like', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('like_id_seq'::regclass)"))
    op.alter_column('discount', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('discount_id_seq'::regclass)"))
    op.alter_column('delivery_process', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('delivery_process_id_seq'::regclass)"))
    op.alter_column('courier_profile', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('courier_profile_id_seq'::regclass)"))
    op.alter_column('country', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('country_id_seq'::regclass)"))
    op.alter_column('comment', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('comment_id_seq'::regclass)"))
    op.alter_column('category', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('category_id_seq'::regclass)"))
    op.alter_column('bucket_product', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('bucket_product_id_seq'::regclass)"))
    op.alter_column('bucket', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('bucket_id_seq'::regclass)"))
    op.alter_column('audit_log', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('audit_log_id_seq'::regclass)"))
    op.drop_index(op.f('ix_role_request_id'), table_name='role_request')
    op.drop_table('role_request')
    # ### end Alembic commands ###
