"""v6.0 add discount

Revision ID: f3c34439ec6c
Revises: 23821ec0291f
Create Date: 2026-08-14 14:31:27.948950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3c34439ec6c"
down_revision: Union[str, Sequence[str], None] = "23821ec0291f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discount",
        sa.Column("product_id", sa.SmallInteger(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("percent", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_deleted", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_staff", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_admin", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_courier", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "is_courier", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_admin", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_staff", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_deleted", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_table("discount")
    # ### end Alembic commands ###
