"""v6.1 add user rating

Revision ID: fdbf07b12c8e
Revises: f3c34439ec6c
Create Date: 2026-08-17 17:35:00.925582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdbf07b12c8e"
down_revision: Union[str, Sequence[str], None] = "f3c34439ec6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_rating",
        sa.Column("user_id", sa.SmallInteger(), nullable=True),
        sa.Column("product_id", sa.SmallInteger(), nullable=True),
        sa.Column("ball", sa.SmallInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(op.f("discount_product_id_fkey"), "discount", type_="foreignkey")
    op.drop_column("discount", "product_id")
    op.add_column("product", sa.Column("discount_id", sa.SmallInteger(), nullable=True))
    op.create_foreign_key(
        None, "product", "discount", ["discount_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("product", "liked_count")
    op.drop_column("product", "rating")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column("rating", sa.SMALLINT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "product",
        sa.Column("liked_count", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "product", type_="foreignkey")
    op.drop_column("product", "discount_id")
    op.add_column(
        "discount",
        sa.Column("product_id", sa.SMALLINT(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("discount_product_id_fkey"),
        "discount",
        "product",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_table("user_rating")
    # ### end Alembic commands ###
